<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */


class Boutique {

	private $boutique_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'boutique_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'boutique_page_init' ) );
	}

	public function boutique_add_plugin_page() {

		$data_user =get_userdata( get_current_user_id() );
	
		$displayed_name = ($data_user->roles[0] == 'administrator' || $data_user->roles[0] == 'admin_artiste') ? 'Commandes' : 'Panier' ;		

		add_menu_page(
			'Boutique', // page_title
			$displayed_name, // menu_title
			'read', // capability
			$displayed_name, // menu_slug
			array( $this, 'boutique_create_admin_page' ), // function
			'dashicons-cart', // icon_url
			55 // position
		);

	}

	public function boutique_create_admin_page() {
        $this->boutique_options = get_option( 'boutique_option_name' );/**Boulean (false)*/?> 

<!-- Appel de l'affichage -->
		<div class="wrap">

            <?php require_once __DIR__.'/../views/market.php'?>
		
		</div>
<!-- Appel de l'affichage -->

    <?php }
    

	public function boutique_page_init() {
		register_setting(
			'boutique_option_group', // option_group
			'boutique_option_name', // option_name
			array( $this, 'boutique_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'boutique_setting_section', // id
			'Settings', // title
			array( $this, 'boutique_section_info' ), // callback
			'boutique-admin' // page
		);

	}

}